#ifndef INC_LCD_LCD_STRINGS_MENU_H_
#define INC_LCD_LCD_STRINGS_MENU_H_

#include "lcd_alphabet_hebrew.h"


typedef enum {
	STR_HEADER_MENU = 0,
	STR_HEADER_FAULT_IND,
	STR_HEADER_ALARM_INFO,
	STR_HEADER_SIREN,
	STR_HEADER_MESSAGES,
	STR_HEADER_PLAY_MESSAGES,
	STR_HEADER_ANNOUNCEMENT,
	STR_HEADER_SILENT_TEST,
	STR_HEADER_BATTERIES_TEST,
	STR_HEADER_APLIFIERS_TEST,
	STR_HEADER_DRIVERS_TEST,
	STR_HEADER_TIME_AND_DATE,
	STR_HEADER_LANGUAGES,

	STR_SIREN,
	STR_MESSAGES,
	STR_ANNOUNCEMENT,
	STR_TESTS,
	STR_REPORT,
	STR_MAINTENANCE,

	STR_FAULT_IND,

	STR_SILENT_TEST,
	STR_BATTERIES_TEST,
	STR_APLIFIERS_TEST,
	STR_DRIVERS_TEST,

	STR_TIME_AND_DATE,
	STR_LANGUAGES,



} MenuStrings;

#endif /* INC_LCD_LCD_STRINGS_MENU_H_ */
